deployUrl=file:///Users/cer/.m2/testdeploy

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

springBootVersion=3.4.7
eventuatePluginsGradleVersion=0.15.0.BUILD-SNAPSHOT
junitVersion=5.12.2
junitPlatformLauncherVersion=1.12.2

version=0.6.0-SNAPSHOT
