dependencies {
    compileOnly "jakarta.persistence:jakarta.persistence-api:$jakartaPersistenceApiVersion"
    implementation "org.apache.commons:commons-lang3:$commonsLang3Version"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
